image: Visual Studio 2017
environment:
  SnkSecret:
    secure: Mpa4faeUiC2uggKSC5ZgiA==
cache:
- src\packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'
- '%LocalAppData%\NuGet\v3-cache'
build_script:
- ps: .\build-utils\Build.ps1
artifacts:
- path: '*.zip'
- path: '*.nupkg'
test: off
deploy:
- provider: S3
  access_key_id:
    secure: suuUVO/OK/7edFaS0HYlm9ouHqd4SIMt8FAE/iAnRR4=
  secret_access_key:
    secure: Nh6AbaBk7P++ymDgtuY7OmkGoXR8s1X+lm5sIZ2Ao39Bw52HLhuPoqy8O3DsgMTQ
  bucket: packages.couchbase.com
  folder: clients/net/2.4/
  artifact: /.*\.zip/
  set_public: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/couchbasenetclient/api/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
