version: 2.4.0.{build}
configuration: Release
init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME".TrimStart("v") }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  SnkSecret:
    secure: Mpa4faeUiC2uggKSC5ZgiA==
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
- ps: nuget install secure-file -ExcludeVersion
before_build:
- ps: nuget restore .\src\couchbase-net-client.sln
- ps: .\secure-file\tools\secure-file.exe -decrypt .\build-utils\Couchbase.snk.enc -secret $env:SnkSecret -out .\Couchbase.snk
- ps: Copy-Item .\Couchbase.snk .\Src\Couchbase\Couchbase.snk
- ps: Copy-Item .\Couchbase.snk .\Src\Couchbase.NetStandard\Couchbase.snk
- ps: Get-Content .\src\Couchbase\Properties\AssemblyInfo.cs | Where { $_ -notmatch "InternalsVisibleTo" } | Out-File .\src\Couchbase\Properties\AssemblyInfo.cs
build_script:
- cmd: msbuild Src\Couchbase\Couchbase.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=Couchbase.snk
- cmd: msbuild Src\Couchbase.NetStandard\Couchbase.NetStandard.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=Couchbase.snk
after_build:
- ps: Copy-Item -Path .\Src\Couchbase\bin\Release -Filter "Couchbase.*" -Destination .\binaries\net45 -Recurse
- ps: Copy-Item -Path .\Src\Couchbase.NetStandard\bin\Release -Filter "Couchbase.*" -Destination .\binaries\netstandard1.5 -Recurse
- ps: Compress-Archive -Path .\binaries\* -CompressionLevel Optimal -DestinationPath .\Couchbase-Net-Client-$env:APPVEYOR_BUILD_VERSION.zip
- ps: Push-AppveyorArtifact **\*.zip
- ps: nuget pack .\src\Couchbase\Couchbase.nuspec -Properties "Configuration=Release;Platform=AnyCPU;" -version "$env:APPVEYOR_BUILD_VERSION"
- ps: Push-AppveyorArtifact **\*.nupkg
test: off
deploy:
- provider: GitHub
  artifact: /.*\.zip/
  auth_token:
    secure: SKZPuqPpuYCGDlPa2hEJ6NmjNBWJ9J60/kM7Y5cEtvm3EHrYX5j3VhV2KV5os5gA
  on:
    appveyor_repo_tag: true
